version: "3"
services:
  caddy:
    image: dtcokr/caddy
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    networks:
      - caddy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/www:/www"
    restart: always
    labels:
      caddy: ":2015"
      caddy.root: "/www"
networks:
  caddy:
