version: "3"
services:
  caddy:
    image: dtcokr/caddy
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    networks:
      - caddy
    volumes:
      - "$HOME/.caddy:/root/.caddy"
      - "/www:/www"
    restart: always
networks:
  caddy:
